/* Local UI test fixture only. Not included in either deployment. */
(()=>{
const today=new Date().toLocaleDateString('en-CA'),tomorrow=new Date(Date.now()+86400000).toLocaleDateString('en-CA');
const initial={courses:[],schedule:[{id:'class-1',type:'class',date:today,start:'10:00',end:'11:15',title:'Introduction to Psychology',location:'Social Sciences 204',color:'#7eaed6'},{id:'class-2',type:'class',date:today,start:'13:00',end:'14:15',title:'College Algebra',location:'Science Hall 112',color:'#a995c6'},{id:'event-1',type:'event',date:today,start:'15:30',end:'16:30',title:'Study group',location:'Library',color:'#c3a56e'}],homework:[{id:'hw-1',date:today,time:'23:59',title:'Chapter 4 reading',course:'Introduction to Psychology',status:'pending',color:'#7eaed6'}],exams:[{id:'exam-1',date:tomorrow,time:'10:00',title:'Psychology midterm',course:'Introduction to Psychology',status:'pending',color:'#7eaed6'}],reminders:[{id:'r-1',date:today,time:'09:00',title:'Print study guide',status:'pending',color:'#bda981'}],settings:{name:'Test Student',email:'test@example.test'}};
const rows=JSON.parse(localStorage.getItem('v2-test-cloud')||'null')||{planner_profiles:{user_id:'fixture-user',profile:{name:'Test Student',email:'test@example.test'},data:initial,updated_at:new Date().toISOString()},planner_canvas_automation:null};
const user={id:'fixture-user',email:'test@example.test',user_metadata:{name:'Test Student'}};
function from(table){let action='select',payload,filters=[],single=false;const q={select(){return q},eq(k,v){filters.push([k,v]);return q},maybeSingle(){single=true;return q},upsert(p){action='upsert';payload=p;return q},insert(p){action='insert';payload=p;return q},update(p){action='update';payload=p;return q},then(resolve,reject){return Promise.resolve().then(()=>{let row=rows[table];if(action==='select')return {data:structuredClone(single?row:row?[row]:[]),error:null};if(action==='update'&&!filters.every(([k,v])=>row?.[k]===v))return {data:[],error:null};rows[table]={...row,...structuredClone(payload)};localStorage.setItem('v2-test-cloud',JSON.stringify(rows));return {data:[structuredClone(rows[table])],error:null}}).then(resolve,reject)}};return q}
window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user,access_token:'fixture-token'}}}),getUser:async()=>({data:{user}}),refreshSession:async()=>({data:{session:{user,access_token:'fixture-token'}}}),signInWithPassword:async()=>({data:{user}}),signOut:async()=>({error:null})},from,channel:()=>({on(){return this},subscribe(){return this}}),removeChannel(){}})};
const native=window.fetch;window.fetch=(url,options)=>String(url).startsWith('/.netlify/')?Promise.resolve(new Response(JSON.stringify({error:'This test fixture does not call external import services.'}),{status:503})):native(url,options);
})();
