const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {merge}=require('../v2/js/data-merge');
const core=import('../supabase/functions/uniplan-canvas-v2/canvas-core.mjs');
const fixture=(parts)=>'BEGIN:VCALENDAR\r\n'+parts.map(p=>'BEGIN:VEVENT\r\n'+p+'\r\nEND:VEVENT').join('\r\n')+'\r\nEND:VCALENDAR';
const clock=new Date('2026-10-01T12:00:00Z');
test('1.5.1 archive matches every captured original file',()=>{const release=path.join(__dirname,'../releases/1.5.1'),manifest=JSON.parse(fs.readFileSync(path.join(release,'manifest.json')));const crypto=require('node:crypto');for(const [file,hash]of Object.entries(manifest.files)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(release,file))).digest('hex'),hash,file);if(file!=='build-deploy.js')assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',file))).digest('hex'),hash,`Original modified: ${file}`)}});
test('merge retains cloud imports and applies local completion',()=>{const base={homework:[{id:'a',title:'A',status:'pending'}]},local={homework:[{id:'a',title:'A',status:'done'}]},remote={homework:[{id:'a',title:'Changed on another device',status:'pending'},{id:'b',title:'Imported'}]};assert.deepEqual(merge(base,local,remote),{homework:[{id:'a',title:'Changed on another device',status:'done'},{id:'b',title:'Imported'}]})});
test('merge honors deletions and independent settings',()=>{assert.deepEqual(merge({homework:[{id:'a'}],settings:{name:'A',theme:'classic'}},{homework:[],settings:{name:'B',theme:'classic'}},{homework:[{id:'a'},{id:'b'}],settings:{name:'A',theme:'ocean'}}),{homework:[{id:'b'}],settings:{name:'B',theme:'ocean'}})});
test('Canvas URL validation rejects alternate hosts, credentials, and ports',async()=>{const {validateFeed}=await core;assert.match(validateFeed('https://school.instructure.com/feeds/calendars/abc.ics'),/abc/);for(const url of ['http://school.instructure.com/feeds/calendars/a.ics','https://instructure.com.evil.test/feeds/calendars/a.ics','https://a:b@school.instructure.com/feeds/calendars/a.ics','https://school.instructure.com:444/feeds/calendars/a.ics','https://127.0.0.1/feeds/calendars/a.ics'])assert.throws(()=>validateFeed(url))});
test('Canvas dates use user timezone, not server timezone',async()=>{const {parseFeed}=await core;const items=parseFeed(fixture(['UID:one\r\nSUMMARY:[PSY 101] Reading\r\nDTSTART:20261002T065900Z','UID:two\r\nSUMMARY:Midterm [PSY 101]\r\nDTSTART;TZID=America/New_York:20261006T100000']),'America/Los_Angeles',clock);assert.equal(items[0].date,'2026-10-01');assert.equal(items[0].time,'23:59');assert.equal(items[1].time,'07:00');assert.equal(items[1].kind,'exam')});
test('all-day tasks retain no invented due time; cancelled/past entries excluded',async()=>{const {parseFeed}=await core;const items=parseFeed(fixture(['UID:a\r\nSUMMARY:Reading\r\nDTSTART;VALUE=DATE:20261003','UID:b\r\nSUMMARY:Cancelled\r\nDTSTART:20261003T120000Z\r\nSTATUS:CANCELLED','UID:c\r\nSUMMARY:Old\r\nDTSTART:20260901T120000Z']),'UTC',clock);assert.equal(items.length,1);assert.equal(items[0].time,'')});
test('imports preserve completed entries and avoid duplicate feed UIDs',async()=>{const {addNewItems}=await core;const data={homework:[{id:'existing',canvasFeedUid:'a',status:'done',title:'Edited',notes:'Keep',date:'2026-10-01',course:'PSY'}],exams:[],schedule:[],settings:{}};const result=addNewItems(data,[{uid:'a',title:'Feed title',kind:'homework',date:'2026-10-02',course:'PSY'},{uid:'b',title:'Quiz',kind:'exam',date:'2026-10-02',course:'PSY',time:''},{uid:'b',title:'Quiz',kind:'exam',date:'2026-10-02',course:'PSY',time:''}],()=> 'new');assert.equal(result.added,1);assert.deepEqual(result.data.homework,data.homework);assert.equal(data.exams.length,0);assert.equal(result.data.exams[0].canvasFeedUid,'b')});
test('imports skip items already manually imported as reminders and match class colors',async()=>{const {addNewItems}=await core;const data={homework:[],exams:[],reminders:[{schoolImportId:'canvas-feed:a'}],schedule:[{id:'class',type:'class',title:'PSY 101',color:'#123456'}],settings:{}};const r=addNewItems(data,[{uid:'a',title:'R',kind:'homework',course:'PSY 101',date:'2026-10-03'},{uid:'b',title:'B',kind:'homework',course:'PSY 101',date:'2026-10-03'}],()=> 'new');assert.equal(r.added,1);assert.equal(r.data.homework[0].color,'#123456')});
test('supabase configuration and planner schema are shared, local cache/version are independent',()=>{assert.equal(fs.readFileSync(path.join(__dirname,'../v2/js/config.js'),'utf8'),fs.readFileSync(path.join(__dirname,'../js/config.js'),'utf8'));const s=fs.readFileSync(path.join(__dirname,'../v2/js/app.js'),'utf8');assert.match(s,/WHATS_NEW_VERSION = "2.0"/);assert.match(s,/SUPABASE_TABLE = "planner_profiles"/);assert.match(s,/STORAGE_KEY = "uniplan-2.0-data"/)});
async function handlerWith(fetchImpl){const {stripTypeScriptTypes}=require('node:module');const src=fs.readFileSync(path.join(__dirname,'../supabase/functions/uniplan-canvas-v2/index.ts'),'utf8').replace(/^import .*?;\n/,'');const context={...(await core),fetch:fetchImpl,Response,AbortSignal,Date,URL,TextDecoder,crypto:require('node:crypto').webcrypto,Deno:{env:{get:key=>({SUPABASE_URL:'https://test.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'server-only',UNIPLAN_CRON_SECRET:'scheduler-secret'})[key]},serve:fn=>context.handler=fn}};vm.createContext(context);vm.runInContext(stripTypeScriptTypes(src),context);return context.handler}
test('Canvas endpoint rejects missing or expired authentication before accessing planner data',async()=>{let calls=0;const handler=await handlerWith(async()=>{calls++;return new Response('{}',{status:401})});let r=await handler(new Request('https://test',{method:'POST',body:'{"action":"sync"}'}));assert.equal(r.status,401);assert.equal(calls,0);r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer expired'},body:'{"action":"sync"}'}));assert.equal(r.status,401);assert.equal(calls,1)});
test('manual sync requires automatic opt-in and does not fetch someone else’s feed',async()=>{const calls=[];const handler=await handlerWith(async(url)=>{calls.push(url);return new Response(JSON.stringify(url.endsWith('/auth/v1/user')?{id:'owner'}:[{user_id:'owner',mode:'manual'}]))});const r=await handler(new Request('https://test',{method:'POST',headers:{Authorization:'Bearer valid'},body:'{"action":"sync","user_id":"other"}'}));assert.equal(r.status,400);assert.ok(calls[1].includes('user_id=eq.owner'));assert.equal(calls.length,2)});
test('class next assignment excludes completed work and keeps overdue work first',()=>{const source=fs.readFileSync(path.join(__dirname,'../v2/js/v2-runtime.js'),'utf8');const fn=source.slice(source.indexOf('function v2NextAssignment('));const context={state:{data:{homework:[{title:'Done',course:'PSY',date:'2026-01-01',status:'done'},{title:'Next',course:'PSY',date:'2026-10-10'},{title:'Overdue',course:' psy ',date:'2026-09-01'},{title:'Other',course:'MATH',date:'2026-01-01'}]}},getNextVisibleOccurrences:x=>x,compareByDateTime:(a,b)=>a.date.localeCompare(b.date)};vm.createContext(context);vm.runInContext(fn,context);assert.equal(context.v2NextAssignment('PSY').title,'Overdue');assert.equal(context.v2NextAssignment('Missing'),undefined)});
test('release build makes both entry points 2.0 while retaining archive',()=>{const {buildV2}=require('../build-v2');const temp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'uniplan-release-'));try{fs.cpSync(path.join(__dirname,'../v2'),path.join(temp,'v2'),{recursive:true});fs.mkdirSync(path.join(temp,'releases/1.5.1'),{recursive:true});fs.writeFileSync(path.join(temp,'releases/1.5.1/index.html'),'original');buildV2(temp);for(const name of ['index.html','mobile.html']){const html=fs.readFileSync(path.join(temp,'deploy',name),'utf8');assert.match(html,/<base href="\.\/v2\/">/);assert.match(html,/UniPlan 2.0/)}assert.equal(fs.readFileSync(path.join(temp,'deploy/releases/1.5.1/index.html'),'utf8'),'original')}finally{fs.rmSync(temp,{recursive:true,force:true})}});
